###
POST localhost:8087/matb/inquire
Content-Type: application/x-www-form-urlencoded

question=List all OA Clients with a reference of less than 10 - note that most references are in the format of 7 digits NNNNNNN

###

POST localhost:8087/matb/inquire
Content-Type: application/x-www-form-urlencoded

question=Can you turn this match into a SQL statement into a table called PROPOSED_CONTRA with the id, the name, and address of the match